name: job-posting-nlp
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pandas
  - numpy
  - scikit-learn
  - matplotlib
  - plotly
  - cufflinks-py
  - pip
  - jupyter_core
  - wordcloud
  - beautifulsoup4
  - lxml
